<?php
$t_language_text_section_content_array = [

    //module configuration
    'MODULE_PAYMENT_UNZER_TEXT_TITLE' => 'Unzer Payments',
    'MODULE_PAYMENT_UNZER_TEXT_DESC' => 'Enables payment with Unzer payment methods.',
    'MODULE_PAYMENT_UNZER_STATUS_TITLE' => 'Activate payment module',
    'MODULE_PAYMENT_UNZER_STATUS_DESC' => 'Do you want to accept payments with Unzer?',
    'MODULE_PAYMENT_UNZER_SORT_ORDER_TITLE' => 'Display order',
    'MODULE_PAYMENT_UNZER_SORT_ORDER_DESC' => 'Order of display. Smallest number is displayed first.',
    'MODULE_PAYMENT_UNZER_ALLOWED_TITLE' => 'Allowed zones',
    'MODULE_PAYMENT_UNZER_ALLOWED_DESC' => 'Individually specify the zones that should be allowed for this module. (e.g., AT,DE (if empty, all zones will be allowed))',
    'MODULE_PAYMENT_UNZER_ZONE_TITLE' => 'Payment zone',
    'MODULE_PAYMENT_UNZER_ZONE_DESC' => 'If a zone is selected, the payment method will only apply to that zone.',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_AUTHORIZED_TITLE' => 'Order status after authorization',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_AUTHORIZED_DESC' => '',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_CAPTURED_TITLE' => 'Order status after payment capture',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_CAPTURED_DESC' => '',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_CHARGEBACK_TITLE' => 'Order status after chargeback',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_CHARGEBACK_DESC' => '',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_REFUNDED_TITLE' => 'Order status after refund',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_REFUNDED_DESC' => '',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_TRIGGER_REFUND_TITLE' => 'Order status to trigger a refund',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_TRIGGER_REFUND_DESC' => '',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_TRIGGER_CAPTURE_TITLE' => 'Order status to trigger a payment capture',
    'MODULE_PAYMENT_UNZER_ORDER_STATUS_ID_TRIGGER_CAPTURE_DESC' => '',
    'MODULE_PAYMENT_UNZER_PUBLIC_KEY_TITLE' => 'Public Key',
    'MODULE_PAYMENT_UNZER_PUBLIC_KEY_DESC' => '',
    'MODULE_PAYMENT_UNZER_PRIVATE_KEY_TITLE' => 'Private Key',
    'MODULE_PAYMENT_UNZER_PRIVATE_KEY_DESC' => '',
    'MODULE_PAYMENT_UNZER_TEXT_INFO' => '',
    'MODULE_PAYMENT_UNZER_CONFIGURE_METHODS' => 'Configure payment methods',
    'MODULE_PAYMENT_UNZER_CONFIGURE_WEBHOOKS' => 'Configure webhooks',

    //payment methods
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_EPS'=>'EPS',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_IDEAL'=>'iDEAL',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_ALIPAY'=>'Alipay',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_WECHATPAY'=>'WeChat Pay',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_PREPAYMENT'=>'Prepayment',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_APPLEPAY'=>'Apple Pay',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_SEPA-DIRECT-DEBIT-SECURED'=>'SEPA Direct Debit Secured',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_GOOGLEPAY'=>'Google Pay',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_PIS'=>'PIS',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_PAYPAL'=>'PayPal',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_TWINT'=>'TWINT',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_KLARNA'=>'Klarna',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_SEPA-DIRECT-DEBIT'=>'SEPA Direct Debit',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_POST-FINANCE-CARD'=>'Post Finance Card',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_SOFORT'=>'Sofort',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_CARD'=>'Credit Card',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_PRZELEWY24'=>'Przelewy24',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_POST-FINANCE-EFINANCE'=>'Post Finance eFinance',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_INVOICE-SECURED'=>'Invoice Secured',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_INVOICE'=>'Invoice',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_INSTALLMENT-SECURED'=>'Installment Secured',
    'MODULE_PAYMENT_UNZER_PAYMENT_METHOD_LABEL_BANCONTACT'=>'Bancontact',

    //payment method configuration page
    'UNZER_CONFIGURATION_TITLE' => 'Unzer Payment Methods Configuration',
    'UNZER_CONFIGURATION_INTRO' => 'Here you can configure Unzer payment methods.',
    'UNZER_OPTION_LABEL_LOG_LEVEL_DEBUG' => 'Debug (log everything)',
    'UNZER_OPTION_LABEL_LOG_LEVEL_ERROR' => 'Error',
    'UNZER_OPTION_LABEL_AUTHORIZE' => 'Authorization/Reservation',
    'UNZER_OPTION_LABEL_CAPTURE' => 'Immediate payment capture',
    'UNZER_ORDER_STATUS_UNCHANGED' => 'Leave status unchanged',
    'UNZER_CONFIGURATION_SAVE'=>'Save',

    //webhook admin page
    'UNZER_WEBHOOKS_TITLE'=>'Unzer Webhooks',
    'UNZER_WEBHOOKS_INTRO'=>'Here you can configure Unzer webhooks.',
    'UNZER_WEBHOOKS_DELETE'=>'Delete',
    'UNZER_WEBHOOKS_REGISTER'=>'Register webhook now',
    'UNZER_WEBHOOKS_REGISTERED'=>'Webhook registered ✅',
    'UNZER_WEBHOOKS_NOT_REGISTERED'=>'Webhook not registered. Please register the webhook by clicking this button:',

    //transaction
    'UNZER_DO_REFUND'=>'Refund amount',
    'UNZER_DO_CAPTURE'=>'Capture amount',
    'UNZER_DO_CANCEL'=>'Cancel payment',
    'UNZER_TRANSACTIONS'=>'Transactions',
    'UNZER_OVERVIEW'=>'Overview',
    'UNZER_AMOUNT_REMAINING'=>'Amount remaining',
    'UNZER_AMOUNT_CAPTURED'=>'Amount captured',
    'UNZER_AMOUNT_REFUNDED'=>'Amount refunded',

    //payment instructions
    'UNZER_PAYMENT_INSTRUCTIONS'=>'Please transfer the amount to the following account:',
    'UNZER_ACCOUNT_HOLDER'=>'Account holder',
    'UNZER_ACCOUNT_IBAN'=>'IBAN',
    'UNZER_ACCOUNT_BIC'=>'BIC',
    'UNZER_ACCOUNT_DESCRIPTOR'=>'Payment reference',

    'UNZER_GENERIC_ERROR_MESSAGE'=>'The payment was canceled. Please try again.',

];
